In [1]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from yolov3.modules import DarknetB

In [4]:
cfg_path = 'config/yolov3/yolov3_320_c_6.cfg'
wts_path = 'config/yolov3/yolov3.weights'

In [7]:
model = DarknetB(cfg_path)
model.load_weights(wts_path)

In [8]:
x = torch.rand(2, 3, 320, 320)

In [9]:
y = model(x)

In [12]:
len(y)

3

In [15]:
y[0]

{'anchors': [(116, 90), (156, 198), (373, 326)],
 'num_classes': 6,
 'input_dim': 320,
 'output': tensor([[[[ 1.1269, -0.2024,  0.5481,  ..., -0.6615, -0.8160, -0.1666],
           [ 1.3108,  0.2750,  0.2313,  ...,  0.3191, -0.8086,  1.0598],
           [ 0.4322,  0.5664,  0.5397,  ..., -0.3115, -0.6983, -0.1446],
           ...,
           [ 0.3598,  0.5925,  0.6279,  ...,  0.0497, -0.2082, -0.0788],
           [ 0.5359,  0.7291,  0.8717,  ...,  0.4512,  0.0611,  0.1450],
           [ 0.2622,  0.2972,  0.4544,  ...,  0.2357,  0.0063,  0.1291]],
 
          [[-0.3456,  0.8392, -0.1021,  ...,  1.7402,  0.7626,  0.8527],
           [ 1.3799,  1.6938,  0.1649,  ...,  2.4649,  0.4684,  0.3001],
           [ 0.5828,  0.0600, -0.0133,  ...,  0.6011, -0.0147,  1.1927],
           ...,
           [ 0.0801, -0.5036, -0.3729,  ..., -0.4100, -0.2040,  0.1527],
           [ 0.3481,  0.1430, -0.0082,  ...,  0.1669,  0.0995,  0.3049],
           [ 0.0927, -0.0447, -0.0570,  ...,  0.4189,  0.1900,  0

In [37]:
class MyFunc(nn.Module):
    def __init__(self):
        super(MyFunc, self).__init__()
    
    def forward(self, x):
        x = x
        y = torch.softmax(x, dim=1)
        z = torch.sigmoid(x)
        return y, z

In [38]:
m = MyFunc()

In [42]:
x = torch.randint(0, 10, (10, 3)).type(torch.float32)

In [43]:
m(x)

(tensor([[8.7560e-01, 5.8998e-03, 1.1850e-01],
         [6.6764e-03, 9.9087e-01, 2.4561e-03],
         [2.3556e-03, 9.5033e-01, 4.7314e-02],
         [4.7385e-02, 8.6788e-04, 9.5175e-01],
         [9.0944e-01, 4.5279e-02, 4.5279e-02],
         [1.8088e-03, 7.2974e-01, 2.6845e-01],
         [2.4473e-01, 6.6524e-01, 9.0031e-02],
         [9.6466e-01, 1.7668e-02, 1.7668e-02],
         [9.9241e-01, 6.6868e-03, 9.0496e-04],
         [6.6764e-03, 9.9087e-01, 2.4561e-03]]),
 tensor([[0.9933, 0.5000, 0.9526],
         [0.7311, 0.9975, 0.5000],
         [0.9526, 0.9999, 0.9975],
         [0.9933, 0.7311, 0.9997],
         [0.9526, 0.5000, 0.5000],
         [0.7311, 0.9991, 0.9975],
         [0.9997, 0.9999, 0.9991],
         [0.9991, 0.9526, 0.9526],
         [0.9999, 0.9820, 0.8808],
         [0.8808, 0.9991, 0.7311]]))

In [44]:
a.grad

tensor([2., 0.])